name: Linux

# only run most recent workflow in branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
    - README.md
    - 'docs/**'
    types: [ opened, reopened, synchronize ]

jobs:
   Kokkos-040200-OpenMPI-OpenMP-Release:
    env:
      KOKKOS_SRC: ${{ github.workspace }}/_deps/kokkos
      KOKKOS_BUILD: ${{ github.workspace }}/_deps/kokkos-build
      KOKKOS_INSTALL: ${{ github.workspace }}/_deps/kokkos-install
      COMM_SRC: ${{ github.workspace }}
      COMM_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Install MPI
        run: |
          sudo apt-get update && sudo apt-get install -y libopenmpi-dev openmpi-bin cmake
          which mpirun
          mpirun --version
          which mpicxx
          mpicxx --version
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - name: Build Kokkos
        run: |
          git clone https://github.com/kokkos/kokkos.git "$KOKKOS_SRC"
          cd "$KOKKOS_SRC" && git checkout 4.2.00
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_NATIVE=ON
          cmake --build "$KOKKOS_BUILD" --parallel $(nproc) -t install
      - name: Build KokkosComm
        run: |
          cmake -S "$COMM_SRC" -B "$COMM_BUILD" -DCMAKE_CXX_FLAGS="-Werror" -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DKokkosComm_ENABLE_TESTS=ON -DKokkosComm_ENABLE_PERFTESTS=ON
          VERBOSE=1 cmake --build "$COMM_BUILD"
      - name: Test KokkosComm
        run: |
          ctest -V --test-dir "$COMM_BUILD"
   Kokkos-040200-MPICH-OpenMP-Debug:
    env:
      KOKKOS_SRC: ${{ github.workspace }}/_deps/kokkos
      KOKKOS_BUILD: ${{ github.workspace }}/_deps/kokkos-build
      KOKKOS_INSTALL: ${{ github.workspace }}/_deps/kokkos-install
      COMM_SRC: ${{ github.workspace }}
      COMM_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install MPI
        run: |
          sudo apt-get update && sudo apt-get install -y mpich cmake
          which mpirun
          mpirun --version
          which mpicxx
          mpicxx --version
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Kokkos
        run: |
          git clone https://github.com/kokkos/kokkos.git "$KOKKOS_SRC"
          cd "$KOKKOS_SRC" && git checkout 4.2.00
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Debug -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_NATIVE=ON
          cmake --build "$KOKKOS_BUILD" --parallel $(nproc) -t install
      - name: Build KokkosComm
        run: |
          cmake -S "$COMM_SRC" -B "$COMM_BUILD" -DCMAKE_CXX_FLAGS="-Werror" -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Debug -DKokkosComm_ENABLE_TESTS=ON -DKokkosComm_ENABLE_PERFTESTS=ON
          VERBOSE=1 cmake --build "$COMM_BUILD"
      - name: Test KokkosComm
        run: |
          ctest -V --test-dir "$COMM_BUILD"
